version: "3"

services:
  node:
    image: node:16
    container_name: all_for_one
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password123456
      HOSTNAME: db

  db:
    container_name: all_for_one_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123456

networks:
  # Utilizarei a rede padrão que é criada automaticamente
  default:
    # Renomeia a rede default
    name: all_for_one_net

